version: "3.7"
services:
  db:
    image: mysql
    container_name: go_template_db
    command: mysqld --user=root
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: go_template
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - template
  migrate:
    image: migrate/migrate
    container_name: go_template_db_migrate
    environment:
      DB_URL: mysql://user:password@tcp(db:3306)/go_template
    volumes:
      - ./migrations:/migrations
    networks:
      - template
    depends_on:
      - db
networks:
  template: